import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";
import "./globals.css";
import { MessageProvider } from "@/context/message-context";
import { StoredUsernameProvider } from "@/context/stored-username-context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MessageProvider>
          <StoredUsernameProvider>
            <Header />
            {children}
          </StoredUsernameProvider>
        </MessageProvider>
      </body>
    </html>
  );
}
