import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";
import "./globals.css";
import { MessageProvider } from "@/context/message-context";
import { StoredUsernameProvider } from "@/context/stored-username-context";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";

export const metadata: Metadata = {
  title: "Beautiful-Form-Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className}>
        <MessageProvider>
          <StoredUsernameProvider>
            <Header />
            {children}
          </StoredUsernameProvider>
        </MessageProvider>
      </body>
    </html>
  );
}
